#ifndef _SHCOLL_ALLTOALL_H
#define _SHCOLL_ALLTOALL_H 1

#include <shmem/teams.h>

#define SHCOLL_ALLTOALL_DECLARATION(_algo, _type, _typename)                    \
  int shcoll_##_typename##_alltoall_##_algo(                                    \
       shmem_team_t team, _type *dest, const _type *source, size_t nelems);

/* shift_exchange_barrier */
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, float, float)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, double, double)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, char, char)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, short, short)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, int, int)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, long, long)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_barrier, ptrdiff_t, ptrdiff)

/* shift_exchange_counter */
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, float, float)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, double, double)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, char, char)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, short, short)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, int, int)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, long, long)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_counter, ptrdiff_t, ptrdiff)

/* shift_exchange_signal */
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, float, float)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, double, double)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, char, char)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, short, short)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, int, int)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, long, long)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(shift_exchange_signal, ptrdiff_t, ptrdiff)

/* xor_pairwise_exchange_barrier */
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, float, float)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, double, double)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, char, char)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, short, short)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, int, int)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, long, long)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_barrier, ptrdiff_t, ptrdiff)

/* xor_pairwise_exchange_counter */
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, float, float)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, double, double)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, char, char)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, short, short)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, int, int)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, long, long)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_counter, ptrdiff_t, ptrdiff)

/* xor_pairwise_exchange_signal */
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, float, float)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, double, double)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, char, char)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, short, short)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, int, int)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, long, long)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(xor_pairwise_exchange_signal, ptrdiff_t, ptrdiff)

/* color_pairwise_exchange_barrier */
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, float, float)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, double, double)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, char, char)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, short, short)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, int, int)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, long, long)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_barrier, ptrdiff_t, ptrdiff)

/* color_pairwise_exchange_counter */
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, float, float)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, double, double)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, char, char)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, short, short)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, int, int)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, long, long)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_counter, ptrdiff_t, ptrdiff)

/* color_pairwise_exchange_signal */
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, float, float)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, double, double)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, long double, longdouble)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, char, char)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, signed char, schar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, short, short)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, int, int)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, long, long)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, long long, longlong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, unsigned char, uchar)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, unsigned short, ushort)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, unsigned int, uint)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, unsigned long, ulong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, unsigned long long, ulonglong)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, int8_t, int8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, int16_t, int16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, int32_t, int32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, int64_t, int64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, uint8_t, uint8)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, uint16_t, uint16)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, uint32_t, uint32)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, uint64_t, uint64)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, size_t, size)
SHCOLL_ALLTOALL_DECLARATION(color_pairwise_exchange_signal, ptrdiff_t, ptrdiff)

#endif /* ! _SHCOLL_ALLTOALL_H */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             